language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sbarza/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sbarza/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-275488826566"
  bucket_path: "docker-react"
  on:
    branch: master
  acceess_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"