language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sbarza/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sbarza/docker-react npm run test